# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Stella R. Student
tagline:          'Your tagline'
description:      A student journalist at the University of Iowa with a bright future ahead of her in mass communication.
url:              http://lathropd.github.io
baseurl:          /hyde/
shortbaseurl:     /hyde
theme:            'body'
# other options theme-base-08 (red), theme-base-09 (orange), theme-base-0a (yellow), theme-base-0b (green), theme-base-0c (cyan), theme-base-0d (blue), theme-base-0e (magenta), theme-base-0f (brown)

author:
  name:           'Daniel Lathrop'
  url:            https://twitter.com/lathropd

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lathropd/hyde
